Lab6/Lab6/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations; //need for Display()
//This is dataAnnotation for decoration.

namespace Lab6.Models
{
    public class User
    {
        [Key]
        public int PersonID { get; set; } //accidentally named this horribly, auto-refactoring will not work at this point. :(

        //[Required]
        public string creator { get; set; }

        [Display(Name = "First Name")]
        [Required]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required]
        public string LastName { get; set; }

        [Display(Name = "Email Address")]
        [Required]
        [EmailAddress(ErrorMessage = "Invalid Email Address fam")]
        public string EmailAddress { get; set; }

        [Display(Name = "Lifetime Ranch Drank (Gallons)")]
        [Required]
        public float GalRanchConsumed { get; set; } //Guy Fieti Power Level


        //A user has Pets ??? Don't understand what the database really does from this
        public virtual List<Pet> MyPets { get; set; }

        public virtual Wealth MyWealth { get; set; }
    }

}

Lab6/Lab6/Controllers/PetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lab6.Models;
using Lab6.Data;
using Lab6.App_Start;
using Lab6.Services;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Lab6.Controllers
{
    [Authorize]
    public class PetsController : Controller
    {
        private readonly DatabaseAccessI _dataRepository;
        private readonly I_PetServices _petServices;

        public PetsController(DatabaseAccessI dataRepository, I_PetServices petServices)
        {
            _dataRepository = dataRepository;
            _petServices = petServices;
        }

        // GET: Pets; 
        public ActionResult Index()
        {
            var petz = _dataRepository.GetAllPets(System.Web.HttpContext.Current.User.Identity.GetUserName());
            return View(petz);
        }

        // GET: Pets/Details/5 Set today's merchant skill for pet
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet pet = _dataRepository.GetAPetByID(id.Value);
            pet.MerchantSkill = _petServices.GenerateDailyShopAbility(pet);

            if (pet == null)
            {
                return HttpNotFound();
            }
            return View(pet);
        }

        // GET: Pets/Create
        public ActionResult Create()
        {
            string usrname = System.Web.HttpContext.Current.User.Identity.GetUserName();

            var pets = _dataRepository.GetAllPets(usrname);
            ViewBag.GroupList = new MultiSelectList(pets, "PetID", "Nickname");
            ViewBag.UserCashDD = _dataRepository.GetListItemofUsersCash(usrname);
            return View();
        }

        // POST: Pets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PetID,NickName")] Pet pet,
            List<int>UserIds, string CustomUserID)
        {
           //string giveUP = Request.Form.ToString();
            string []UserDDForm = Request.Form.GetValues("UserCashDD");
            string[] SpeciesDDForm = Request.Form.GetValues("petClickedID");

            if (ModelState.IsValid)
            {
                string creator = System.Web.HttpContext.Current.User.Identity.GetUserName();
                int CustomUserEyeD = int.Parse(UserDDForm[0]);
                _dataRepository.BuyPet(100.00, CustomUserEyeD);
                int speeshis = int.Parse(SpeciesDDForm[0]);
                //ApplicationUser _user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());

                if (UserIds != null)
                {
                    pet.Users = new List<User>();
                    //many to many ORM ???
                    foreach (var aUserRef in UserIds)
                    {
                        pet.Users.Add(
                            new User { PersonID = aUserRef }
                            );
                    }
                }
                else {
                    bool alreadyExists = false;
                    if (pet.Users == null)
                    {
                        pet.Users = new List<User>();
                    }
                    else {//Pet already belongs to at least 1 user; don't add any users twice!
                        foreach (var uza in pet.Users)
                        {
                            if (uza.PersonID == CustomUserEyeD) { alreadyExists = true; }
                        }
                    }
                    if (!alreadyExists)
                    {
                        pet.Users.Add(_dataRepository.GetAUserByID(CustomUserEyeD));
                    }
                }
                
                pet.Creator = creator;
                pet.Species = speeshis;
                _dataRepository.AddNewPet(pet);
                

                return RedirectToAction("Index");
            }
            return View(pet);
        }

        // GET: Pets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet pet = _dataRepository.GetAPetByID(id.Value);
            if (pet == null)
            {
                return HttpNotFound();
            }
            return View(pet);
        }

        // POST: Pets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PetID,NickName")] Pet pet)
        {
            if (ModelState.IsValid)
            {
                _dataRepository.UpdatePet(pet);
                return RedirectToAction("Index");
            }
            return View(pet);
        }

        // GET: Pets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet pet = _dataRepository.GetAPetByID(id.Value);
            if (pet == null)
            {
                return HttpNotFound();
            }

            _dataRepository.RemovePet(pet);

            return RedirectToAction("Index");
        }

        // POST: Pets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pet pet = _dataRepository.GetAPetByID(id);
            return RedirectToAction("Index");
        }
    }
}

Lab6/Lab6/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lab6.Models;
using Lab6.Data; //database repo services
using Microsoft.AspNet.Identity;

namespace Lab6.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly DatabaseAccessI _dataRepository;

        public UsersController(DatabaseAccessI dataRepository) {
            _dataRepository = dataRepository;
        }

        // GET: UsersEF
        public ActionResult Index()
        {
            //var persons = _dataRepository.GetAllUsers();
            var persons = _dataRepository.GetAllUsers(System.Web.HttpContext.Current.User.Identity.GetUserName());
            return View(persons);
        }

        
        // GET: UsersEF/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //int nonNullableId = id ?? default(int); ////http://stackoverflow.com/questions/5995317/how-to-convert-c-sharp-nullable-int-to-int
            User user = _dataRepository.GetAUserByID(id.Value); //nullableInt.Value will throw exception here if it is null!

            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: UsersEF/Create
        public ActionResult Create()
        {
            var pets = _dataRepository.GetAllPets();
            ViewBag.GroupList = new MultiSelectList(pets, "PetID", "Nickname");
            return View();
        }

        // POST: UsersEF/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PersonID,FirstName,LastName,EmailAddress,GalRanchConsumed")] User user, 
            List<int>PetIds)
        {
            if (ModelState.IsValid)
            {
                string creatore = System.Web.HttpContext.Current.User.Identity.GetUserName();
                Wealth MyMoney = new Wealth();
                MyMoney.Cash = 300;
                
                // TODO: add UI hook to add pets either in create or seperate service 
                if (PetIds != null)
                {
                    user.MyPets = new List<Pet>();
                    // Add all pets to user's collection of pets
                    foreach (var petNum in PetIds)
                    {
                        user.MyPets.Add(
                            new Pet { PetID = petNum }
                            );
                    }
                }
                user.creator = creatore;
                user.MyWealth = MyMoney;
                _dataRepository.AddNewUser(user);

                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: UsersEF/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = _dataRepository.GetAUserByID(id.Value);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: UsersEF/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PersonID,FirstName,LastName,EmailAddress,GalRanchConsumed")] User user)
        {
            if (ModelState.IsValid)
            {
                _dataRepository.UpdateUser(user);
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: UsersEF/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = _dataRepository.GetAUserByID(id.Value);
            if (user == null)
            {
                return HttpNotFound();
            }

            _dataRepository.RemoveUser(user);

            return RedirectToAction("Index");
        }

        // POST: UsersEF/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = _dataRepository.GetAUserByID(id); //should this be nullable int?
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

Lab6/Lab6/Views/Users/Create.cshtml
@model Lab6.Models.User

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GalRanchConsumed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GalRanchConsumed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GalRanchConsumed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Lab6/Lab6/Views/Users/Delete.cshtml
@model Lab6.Models.User

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GalRanchConsumed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GalRanchConsumed)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Lab6/Lab6/Views/Users/Details.cshtml
@model Lab6.Models.User

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GalRanchConsumed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GalRanchConsumed)
        </dd>
        <dt>
            Pets
        </dt>
        <dd>
            @foreach (var pat in Model.MyPets)
            {
                @*@Html.ActionLink(pat.NickName, "Details", "Pets", new { id = pat.PetID })*@
                @Html.ActionLink(pat.NickName, "Details", "Pets",  new { id = pat.PetID}, null)
                <br>
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PersonID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Lab6/Lab6/Views/Users/Edit.cshtml
@model Lab6.Models.User

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PersonID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GalRanchConsumed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GalRanchConsumed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GalRanchConsumed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Lab6/Lab6/Views/Users/Index.cshtml
@model IEnumerable<Lab6.Models.User>

@{
    ViewBag.Title = "Index";
    int counter = 0;
}
<h2>Your Users</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, htmlAttributes: new { @class = "btn btn-primary btn-lg" })
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GalRanchConsumed)
        </th>
        <th> 
            @Html.DisplayNameFor(model => model.MyWealth.Cash)
        </th>
        <th>
            Num. Pets
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    counter++;
    <tr class="tRowClass">
        <td class="tRowsCol @(@item.FirstName.StartsWith("J") ? "danger" : "")">
            @Html.DisplayFor(modelItem => item.FirstName)
            
        </td>
        <td class="tRowsCol">
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td class="tRowsCol">
            @Html.DisplayFor(modelItem => item.EmailAddress)
        </td>
        <td class="tRowsCol">
            @Html.DisplayFor(modelItem => item.GalRanchConsumed)
        </td>
        <td class="tRowsCol">
            @Html.DisplayFor(modelItem => item.MyWealth.Cash)
        </td>
        <td class="tRowsCol">
            @Html.DisplayFor(modelItem => item.MyPets.Count)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.PersonID }, htmlAttributes: new { @class = "btn btn-primary btn-sm" }) 
            @Html.ActionLink("Details", "Details", new { id = item.PersonID }, htmlAttributes: new { @class = "btn btn-primary btn-sm" }) 
            @Html.ActionLink("Delete", "Delete", new { id = item.PersonID }, htmlAttributes: new { @class = "btn btn-primary btn-sm" })
        </td>
    </tr>
}
    @if (counter > 7)
    {
        <div class="alert alert-info alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Whoa!</strong> That's a lot of users, you should focus on ONE at a time
        </div>
    }

</table>

<button type="button" id="hideT" class="btn btn-info">HIDE TABLE</button>
<button type="button" id="showT" class="btn btn-info">SHOW TABLE</button>
<div id="rowSelecte">

</div>


@section scripts {
    <script>
        $(document).ready(function () {
            //$("button").click(function () {
            //    $("table").toggle();
            //});
            $("#hideT").click(function () {
                $("table").hide();
                //alert("HIDING TABLE");
            });
            $("#showT").click(function () {
                $("table").show();
                //alert("SHOWING TABLE");
            });

            $(".tRowClass").click(function () {
                //$("table").hide();
                var value = $(this).find('.tRowsCol').text().trim();
                //alert("Ya clicked " + value + " row BOI");
                document.getElementById('rowSelecte').innerHTML = "Ya clicked: " + value;
            });

        });
    </script>
}